# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Enable Gradle to auto-download JDK
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true
